name: Proxy docs preview site via www preview site

on: workflow_dispatch

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - id: normalize
        name: Normalize branch name
        run: echo "NORMALIZED_BRANCH=$(echo "$GITHUB_REF" | sed 's|/|-|' | sed 's|.||')" >> $GITHUB_OUTPUT
      - id: test
        name: Test
        run: echo "$BRANCH"
