name: Proxy docs preview site via www preview site

on: [pull_request, workflow_dispatch]

jobs:
  proxy:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ GITHUB_REF }}
    steps:
      - id: normalize
        name: Normalize branch name
        run: echo "NORMALIZED_BRANCH=$(echo "$BRANCH" | sed 's|/|-|' | sed 's|.||')" >> $GITHUB_OUTPUT
      - id: test
        name: Test
        run: echo "$BRANCH"
